version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pathfinder_db
    environment:
      POSTGRES_USER: pathfinder
      POSTGRES_PASSWORD: pathfinder
      POSTGRES_DB: pathfinder
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: pathfinder_backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://pathfinder:pathfinder@postgres:5432/pathfinder

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: pathfinder_frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend