version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pathfinder_db
    environment:
      POSTGRES_USER: pathfinder
      POSTGRES_PASSWORD: pathfinder
      POSTGRES_DB: pathfinder
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: pathfinder_backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: pathfinder
      DB_PASSWORD: pathfinder
      DB_DATABASE: pathfinder

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: pathfinder_frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    environment:
      NODE_OPTIONS: "--max_old_space_size=3072"